### ISSUE TITLE
SUPPORTERSページ改定

### ISSUE THREAD

**Issue by hayasehakariya** [hayasehakariya/WAKAZO_Debug#2]

**Comment by tomihe0720** [comment]
野村氏掲載完了

**Comment by tomihe0720** [comment]
今後システム組み込んで、管理画面からの管理になります

**Comment by tomihe0720** [comment]
【検証】システム組み込み、検証にアップ→反映依頼済み
[仕様]
・管理画面から編集可能
 ・動画はYoutubeの埋め込みコード対応（入力項目「動画」になります）

**Comment by tomihe0720** [comment]
【修正完了】
上記システム組み込み、本番反映済み
