### ISSUE TITLE
SENPAI_Debug

### ISSUE THREAD

**Issue by hayasehakariya** [hayasehakariya/WAKAZO_Debug#8]
コンペページのセンパイの写真が変な位置にあります...(建築、パフォ、イラスト、映像で起きています)
naoki-shitanda [10:52 PM] 
PC,chromeです。

**Comment by hayasehakariya** [comment]
![image](https://user-images.githubusercontent.com/29085975/31501422-32e53b32-afa5-11e7-87f5-46e07c0e90be.png)

**Comment by tomihe0720** [comment]
修正完了
